# Generated by Django 3.1 on 2020-08-08 10:19

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Contenitore', 'verbose_name_plural': 'Contenitori'},
        ),
        migrations.AlterModelOptions(
            name='ddt',
            options={'ordering': ['date'], 'verbose_name': 'Documento di trasporto', 'verbose_name_plural': 'Documenti di trasporto'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_id',
        ),
        migrations.AlterField(
            model_name='container',
            name='ddt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='api.ddt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.utils.short_uuid, max_length=6, primary_key=True, serialize=False),
        ),
    ]
