# Generated by Django 3.1 on 2020-08-13 16:00

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=api.utils.short_uuid, editable=False, max_length=6, unique=True),
        ),
    ]
