# Generated by Django 3.1 on 2020-08-14 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200813_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'EPAL'), (2, 'Pallet grandi'), (3, 'Pallet sdoppiato'), (4, 'Carrelli grandi'), (5, 'Carrelli piccoli'), (6, 'Cestoni'), (7, 'Casse Verdi'), (8, 'Casse Grigie'), (9, 'Presse')], verbose_name='tipo')),
                ('count', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Quantità')),
                ('ddt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pallets', to='api.ddt')),
            ],
            options={
                'verbose_name': 'Contenitore',
                'verbose_name_plural': 'Contenitori',
                'unique_together': {('ddt', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
