# Generated by Django 3.1 on 2020-08-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200820_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddt',
            old_name='creation_time',
            new_name='time',
        ),
    ]
